const BAD_REQUEST = "BAD_REQUEST";
const UNAUTHORIZED = "UNAUTHORIZED";
const FORBIDDEN = "FORBIDDEN";
const TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
const NOT_FOUND = "NOT_FOUND";
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
const UNKNOW_ERROR = "UNKNOW_ERROR";
const NETWORK_ERROR = "NETWORK_ERROR";

export type TApiError =
  | typeof BAD_REQUEST
  | typeof UNAUTHORIZED
  | typeof FORBIDDEN
  | typeof TOO_MANY_REQUESTS
  | typeof NOT_FOUND
  | typeof INTERNAL_SERVER_ERROR
  | typeof UNKNOW_ERROR
  | typeof NETWORK_ERROR;
